// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Ping struct {
	Timestamp string `json:"timestamp"`
}

type Query struct {
}

type Subscription struct {
}
